package ke.energy.model.components.am;



import ke.energy.common.baseclasses.ApplicationModuleImpl;


import ke.energy.common.baseclasses.ViewObjectImpl;

import oracle.jbo.server.ViewLinkImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 26 10:22:02 EAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for cmCurrenciesVO1.
     * @return cmCurrenciesVO1
     */
    public ViewObjectImpl getcmCurrenciesVO1() {
        return (ViewObjectImpl) findViewObject("cmCurrenciesVO1");
    }


    /**
     * Container's getter for cmTreeMenuLevel2VO1.
     * @return cmTreeMenuLevel2VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel2VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel2VO1");
    }

    /**
     * Container's getter for cmTreeMenuLevel3VO1.
     * @return cmTreeMenuLevel3VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel3VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel3VO1");
    }

    /**
     * Container's getter for cmTreeMenuL2L3VL1.
     * @return cmTreeMenuL2L3VL1
     */
    public ViewLinkImpl getcmTreeMenuL2L3VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL2L3VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel4VO1.
     * @return cmTreeMenuLevel4VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel4VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel4VO1");
    }

    /**
     * Container's getter for cmTreeMenuL3L4VL1.
     * @return cmTreeMenuL3L4VL1
     */
    public ViewLinkImpl getcmTreeMenuL3L4VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL3L4VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel5VO1.
     * @return cmTreeMenuLevel5VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel5VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel5VO1");
    }

    /**
     * Container's getter for cmTreeMenuL4L5VL1.
     * @return cmTreeMenuL4L5VL1
     */
    public ViewLinkImpl getcmTreeMenuL4L5VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL4L5VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel6VO1.
     * @return cmTreeMenuLevel6VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel6VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel6VO1");
    }

    /**
     * Container's getter for cmTreeMenuL5L6VL1.
     * @return cmTreeMenuL5L6VL1
     */
    public ViewLinkImpl getcmTreeMenuL5L6VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL5L6VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel7VO1.
     * @return cmTreeMenuLevel7VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel7VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel7VO1");
    }

    /**
     * Container's getter for cmTreeMenuL6L7VL1.
     * @return cmTreeMenuL6L7VL1
     */
    public ViewLinkImpl getcmTreeMenuL6L7VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL6L7VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel8VO1.
     * @return cmTreeMenuLevel8VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel8VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel8VO1");
    }

    /**
     * Container's getter for cmTreeMenuL7L8VL1.
     * @return cmTreeMenuL7L8VL1
     */
    public ViewLinkImpl getcmTreeMenuL7L8VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL7L8VL1");
    }

    /**
     * Container's getter for cmTreeMenuLevel9VO1.
     * @return cmTreeMenuLevel9VO1
     */
    public ViewObjectImpl getcmTreeMenuLevel9VO1() {
        return (ViewObjectImpl) findViewObject("cmTreeMenuLevel9VO1");
    }

    /**
     * Container's getter for cmTreeMenuL8L9VL1.
     * @return cmTreeMenuL8L9VL1
     */
    public ViewLinkImpl getcmTreeMenuL8L9VL1() {
        return (ViewLinkImpl) findViewLink("cmTreeMenuL8L9VL1");
    }
}

