package ke.energy.model.component.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 14:44:58 EAT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void searchCurrenciesVO(String pCurrencyCode);
}

