package ke.energy.model.component.am;

import ke.energy.common.baseclasses.ApplicationModuleImpl;
import ke.energy.common.baseclasses.ViewObjectImpl;
import ke.energy.model.component.am.common.AppModule;

import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 14:43:38 EAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


    public void searchCurrenciesVO(String pCurrencyCode)
    {
        ViewObjectImpl vo = this.getcmCurrenciesVO1();
        ViewCriteria   vc = vo.getViewCriteria("searchCurrenciesVC");
        vo.setNamedWhereClauseParam("bCurrencyCode",pCurrencyCode);
        vo.applyViewCriteria(vc);
        vo.executeQuery();    
    }

    /**
     * Container's getter for cmCurrenciesVO1.
     * @return cmCurrenciesVO1
     */
    public ViewObjectImpl getcmCurrenciesVO1() {
        return (ViewObjectImpl) findViewObject("cmCurrenciesVO1");
    }
}

