CREATE TABLE CM_CURRENCIES
    (
    CURRENCY_CODE 				VARCHAR(15) 				NOT NULL, 
	NAME                      	VARCHAR(80) 				NOT NULL,
	DESCRIPTION 				VARCHAR(240)						,
	ENABLED_FLAG 				VARCHAR(1) 				    NOT NULL,  
	BASE_PRECISION 				INT(1)		        				, 
	EXTENDED_PRECISION 			INT(2)     							, 
	SYMBOL 						VARCHAR(12)			    			, 
	START_DATE_ACTIVE 			DATETIME							, 
	END_DATE_ACTIVE 			DATETIME							,
	CREATION_DATE 				DATETIME					DEFAULT NOW()		NOT NULL, 
	CREATED_BY 					INT(15)      					NOT NULL, 
	LAST_UPDATE_DATE 			DATETIME 					DEFAULT NOW()		NOT NULL, 
	LAST_UPDATED_BY 			INT(15)      					NOT NULL,
    
    PRIMARY KEY (CURRENCY_CODE)
    
    )