CREATE TABLE ENERGY_ADF.FND_CURRENCIES 
   (	
	CURRENCY_CODE 				VARCHAR2(15) 				NOT NULL, 
	NAME                      	VARCHAR2(80) 				NOT NULL,
	DESCRIPTION 				VARCHAR2(240)						,
	ENABLED_FLAG 				VARCHAR2(1) 				NOT NULL,  
	PRECISION 					NUMBER(1)							, 
	EXTENDED_PRECISION 			NUMBER(2)							, 
	SYMBOL 						VARCHAR2(12)						, 
	START_DATE_ACTIVE 			DATE								, 
	END_DATE_ACTIVE 			DATE								,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15) 				DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15) 				DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15) 				DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.FND_CURRENCIES_CURRENCY_CODE_PK PRIMARY KEY 
	  (
		CURRENCY_CODE
	  )
	  ENABLE
   ); 

   CREATE TABLE ENERGY_ADF.FND_PERIOD_STATUS_TYPES   
   (
	PERIOD_STATUS_TYPE_ID		NUMBER(15)					NOT NULL,
	NAME                      	VARCHAR2(15) 				NOT NULL,
	DESCRIPTION 				VARCHAR2(240)						,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15) 				DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15) 				DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15) 				DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.FND_PERIOD_STATUS_TYPES_PERIOD_STATUS_TYPE_ID_PK PRIMARY KEY 
	  (
		PERIOD_STATUS_TYPE_ID
	  )
	  ENABLE
   ); 
   
	ALTER TABLE ENERGY_ADF.FND_PERIOD_STATUS_TYPES
	ADD CONSTRAINT FND_PERIOD_STATUS_TYPES_NAME_UK UNIQUE 
	(
	  NAME 
	)
	ENABLE;   
   
  CREATE TABLE ENERGY_ADF.HR_BUSINESS_GROUPS
   (	
	BUSINESS_GROUP_ID           NUMBER(15) 					NOT NULL,
	BUSINESS_GROUP_NAME         VARCHAR2(240) 				NOT NULL,
	ADDRESS_LINE_1              VARCHAR2(240)  						,    
	ADDRESS_LINE_2              VARCHAR2(240)      					,
	ADDRESS_LINE_3              VARCHAR2(240)  						,
	TOWN_OR_CITY                VARCHAR2(30)       					,
	COUNTRY                     VARCHAR2(60)       					,
	POSTAL_CODE                 VARCHAR2(30) 						,
	REGION_1                    VARCHAR2(120)      					,
	REGION_2                    VARCHAR2(120)      					,
	REGION_3                    VARCHAR2(120)						,
	TELEPHONE_NUMBER_1          VARCHAR2(60)       					,
	TELEPHONE_NUMBER_2          VARCHAR2(60)       					,	
	TELEPHONE_NUMBER_3          VARCHAR2(60)						,
	START_DATE_ACTIVE 			DATE								, 
	END_DATE_ACTIVE 			DATE								,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.HR_BUSINESS_GROUPS_BUSINESS_GROUP_ID_PK PRIMARY KEY 
	  (
		BUSINESS_GROUP_ID
	  )
	  ENABLE	
   ); 
    

   CREATE TABLE ENERGY_ADF.HR_OPERATING_UNITS
   (	
	OPERATING_UNIT_ID           NUMBER(15) 					NOT NULL,
	BUSINESS_GROUP_ID           NUMBER(15) 					NOT NULL,
	OPERATING_UNIT_NAME         VARCHAR2(240) 				NOT NULL,
	SHORT_CODE                 	VARCHAR2(150)						,
	ADDRESS_LINE_1              VARCHAR2(240)  						,    
	ADDRESS_LINE_2              VARCHAR2(240)      					,
	ADDRESS_LINE_3              VARCHAR2(240)  						,
	TOWN_OR_CITY                VARCHAR2(30)       					,
	COUNTRY                     VARCHAR2(60)       					,
	POSTAL_CODE                 VARCHAR2(30) 						,
	REGION_1                    VARCHAR2(120)      					,
	REGION_2                    VARCHAR2(120)      					,
	REGION_3                    VARCHAR2(120)						,
	TELEPHONE_NUMBER_1          VARCHAR2(60)       					,
	TELEPHONE_NUMBER_2          VARCHAR2(60)       					,	
	TELEPHONE_NUMBER_3          VARCHAR2(60)						,
	START_DATE_ACTIVE 			DATE								, 
	END_DATE_ACTIVE 			DATE								,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.HR_OPERATING_UNITS_OPERATING_UNIT_ID_PK PRIMARY KEY 
	  (
		OPERATING_UNIT_ID
	  )
	  ENABLE		
   ); 
   
	ALTER TABLE ENERGY_ADF.HR_OPERATING_UNITS
	ADD CONSTRAINT HR_OPERATING_UNITS_BUSINESS_GROUP_ID_FK FOREIGN KEY
	(
	  BUSINESS_GROUP_ID
	)
	REFERENCES ENERGY_ADF.HR_BUSINESS_GROUPS
	(
	  BUSINESS_GROUP_ID
	)
	ENABLE;   
	
   CREATE TABLE ENERGY_ADF.GL_CALENDAR_HEADERS
   (	
	GL_CALENDAR_ID           	NUMBER(15) 					NOT NULL,
	GL_CALENDAR_NAME            VARCHAR2(15) 				NOT NULL,
	DESCRIPTION				    VARCHAR2(240) 				NOT NULL,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.GL_CALENDAR_HEADERS_GL_CALENDAR_ID_PK PRIMARY KEY 
	  (
		GL_CALENDAR_ID
	  )
	  ENABLE		
   ); 	
   
   CREATE TABLE ENERGY_ADF.GL_CALENDAR_LINES
   (	
	GL_CALENDAR_LINE_ID         NUMBER(15) 					NOT NULL,
	GL_CALENDAR_ID           	NUMBER(15) 					NOT NULL,	
	PERIOD_YEAR             	NUMBER(15) 					NOT NULL,
	FROM_DATE 					DATE						NOT NULL, 
	TO_DATE		 				DATE						NOT NULL,	
	PERIOD_NAME					VARCHAR2(15) 				NOT NULL,
	PERIOD_NUM              	NUMBER(15)					NOT NULL,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.GL_CALENDAR_LINES_GL_CALENDAR_LINE_ID_PK PRIMARY KEY 
	  (
		GL_CALENDAR_LINE_ID
	  )
	  ENABLE		
   );   

   	ALTER TABLE ENERGY_ADF.GL_CALENDAR_LINES
	ADD CONSTRAINT GL_CALENDAR_LINES_GL_CALENDAR_ID_FK FOREIGN KEY
	(
	  GL_CALENDAR_ID
	)
	REFERENCES ENERGY_ADF.GL_CALENDAR_HEADERS
	(
	  GL_CALENDAR_ID
	)
	ENABLE; 
	
   CREATE TABLE ENERGY_ADF.GL_PERIODS
   (	
	GL_PERIOD_ID         		NUMBER(15) 					NOT NULL,
	OPERATING_UNIT_ID           NUMBER(15) 					NOT NULL,	
	GL_CALENDAR_LINE_ID         NUMBER(15) 					NOT NULL,	
	PERIOD_STATUS_TYPE_ID		NUMBER(15)					NOT NULL,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.GL_PERIODS_GL_PERIOD_ID_PK PRIMARY KEY 
	  (
		GL_PERIOD_ID
	  )
	  ENABLE		
   ); 
   	ALTER TABLE ENERGY_ADF.GL_PERIODS
	ADD CONSTRAINT GL_PERIODS_OPERATING_UNIT_ID_FK FOREIGN KEY
	(
	  OPERATING_UNIT_ID
	)
	REFERENCES ENERGY_ADF.HR_OPERATING_UNITS
	(
	  OPERATING_UNIT_ID
	)
	ENABLE;  
	
   	ALTER TABLE ENERGY_ADF.GL_PERIODS
	ADD CONSTRAINT GL_PERIODS_GL_CALENDAR_LINE_ID_FK FOREIGN KEY
	(
	  GL_CALENDAR_LINE_ID
	)
	REFERENCES ENERGY_ADF.GL_CALENDAR_LINES
	(
	  GL_CALENDAR_LINE_ID
	)
	ENABLE;  
	
   	ALTER TABLE ENERGY_ADF.GL_PERIODS
	ADD CONSTRAINT GL_PERIODS_PERIOD_STATUS_TYPE_ID_FK FOREIGN KEY
	(
	  PERIOD_STATUS_TYPE_ID
	)
	REFERENCES ENERGY_ADF.FND_PERIOD_STATUS_TYPES
	(
	  PERIOD_STATUS_TYPE_ID
	)
	ENABLE;  	

   CREATE TABLE ENERGY_ADF.INV_INVENTORY_ORGANIZATIONS
   (	
	INVENTORY_ORGANIZATION_ID 	NUMBER(15) 					NOT NULL,
	INVENTORY_ORGANIZATION_CODE	VARCHAR2(15)				NOT NULL,
	INVENTORY_ORGANIZATION_NAME	VARCHAR2(250)				NOT NULL,
	OPERATING_UNIT_ID           NUMBER(15) 					NOT NULL,	
	GL_CALENDAR_ID           	NUMBER(15) 					NOT NULL,
	MATERIAL_ACCOUNT			NUMBER(15)					NOT NULL,
	INTRANSIT_INVENTORY_ACCOUNT	NUMBER(15)					NOT NULL,
	COGS_ACCOUNT				NUMBER(15)					NOT NULL,
	PPV_ACCOUNT					NUMBER(15)					NOT NULL,
	ACCRUAL_ACCOUNT				NUMBER(15)					NOT NULL,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.INV_INVENTORY_ORGANIZATIONS_INVENTORY_ORGANIZATION_ID_PK PRIMARY KEY 
	  (
		INVENTORY_ORGANIZATION_ID
	  )
	  ENABLE		
   ); 	
   
   	ALTER TABLE ENERGY_ADF.INV_INVENTORY_ORGANIZATIONS
	ADD CONSTRAINT INV_INVENTORY_ORGANIZATIONS_OPERATING_UNIT_ID_FK FOREIGN KEY
	(
	  OPERATING_UNIT_ID
	)
	REFERENCES ENERGY_ADF.HR_OPERATING_UNITS
	(
	  OPERATING_UNIT_ID
	)
	ENABLE;  
	
   	ALTER TABLE ENERGY_ADF.INV_INVENTORY_ORGANIZATIONS
	ADD CONSTRAINT INV_INVENTORY_ORGANIZATIONS_GL_CALENDAR_ID_FK FOREIGN KEY
	(
	  GL_CALENDAR_ID
	)
	REFERENCES ENERGY_ADF.GL_CALENDAR_HEADERS
	(
	  GL_CALENDAR_ID
	)
	ENABLE; 	
	
   CREATE TABLE ENERGY_ADF.INV_INVENTORY_PERIODS
   (	
	INVENTORY_PERIOD_ID 		NUMBER(15) 					NOT NULL,
	INVENTORY_ORGANIZATION_ID 	NUMBER(15) 					NOT NULL,	
	PERIOD_STATUS_TYPE_ID		NUMBER(15)					NOT NULL,
	CLOSE_DATE					DATE								,
	CREATION_DATE 				DATE					DEFAULT SYSDATE		NOT NULL, 
	CREATED_BY 					NUMBER(15,0) 			DEFAULT 1			NOT NULL, 
	LAST_UPDATE_DATE 			DATE 					DEFAULT SYSDATE		NOT NULL, 
	LAST_UPDATED_BY 			NUMBER(15,0) 			DEFAULT 1			NOT NULL, 	
	LAST_UPDATE_LOGIN 			NUMBER(15,0) 			DEFAULT 1			NOT NULL,
	CONSTRAINT ENERGY_ADF.INV_INVENTORY_PERIODS_INVENTORY_PERIOD_ID_PK PRIMARY KEY 
	  (
		INVENTORY_PERIOD_ID
	  )
	  ENABLE		
   ); 	
   
   	ALTER TABLE ENERGY_ADF.INV_INVENTORY_PERIODS
	ADD CONSTRAINT INV_INVENTORY_PERIODS_INVENTORY_ORGANIZATION_ID_FK FOREIGN KEY
	(
	  INVENTORY_ORGANIZATION_ID
	)
	REFERENCES ENERGY_ADF.INV_INVENTORY_ORGANIZATIONS
	(
	  INVENTORY_ORGANIZATION_ID
	)
	ENABLE;       
   
   	ALTER TABLE ENERGY_ADF.INV_INVENTORY_PERIODS
	ADD CONSTRAINT INV_INVENTORY_PERIODS_PERIOD_STATUS_TYPE_ID_FK FOREIGN KEY
	(
	  PERIOD_STATUS_TYPE_ID
	)
	REFERENCES ENERGY_ADF.FND_PERIOD_STATUS_TYPES
	(
	  PERIOD_STATUS_TYPE_ID
	)
	ENABLE;    